// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgYAij56R0oerq1Yyny8oDtNMebCKN4X4',
    appId: '1:562865729062:web:359c066138bcecee44c0e7',
    messagingSenderId: '562865729062',
    projectId: 'kitaconnectapp',
    authDomain: 'kitaconnectapp.firebaseapp.com',
    storageBucket: 'kitaconnectapp.firebasestorage.app',
    measurementId: 'G-8XY17YE5RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKB9QsDFVcPW4fcRO7g49xCKJSMeWSwHo',
    appId: '1:562865729062:android:4cb917697b8f983544c0e7',
    messagingSenderId: '562865729062',
    projectId: 'kitaconnectapp',
    storageBucket: 'kitaconnectapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbJpQjCkuAx-YyWVt4llg0_G0UUuYMTjo',
    appId: '1:562865729062:ios:4f65c20adc8193dd44c0e7',
    messagingSenderId: '562865729062',
    projectId: 'kitaconnectapp',
    storageBucket: 'kitaconnectapp.firebasestorage.app',
    iosBundleId: 'com.example.kitaconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbJpQjCkuAx-YyWVt4llg0_G0UUuYMTjo',
    appId: '1:562865729062:ios:4f65c20adc8193dd44c0e7',
    messagingSenderId: '562865729062',
    projectId: 'kitaconnectapp',
    storageBucket: 'kitaconnectapp.firebasestorage.app',
    iosBundleId: 'com.example.kitaconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgYAij56R0oerq1Yyny8oDtNMebCKN4X4',
    appId: '1:562865729062:web:d1ca5720cda9583244c0e7',
    messagingSenderId: '562865729062',
    projectId: 'kitaconnectapp',
    authDomain: 'kitaconnectapp.firebaseapp.com',
    storageBucket: 'kitaconnectapp.firebasestorage.app',
    measurementId: 'G-L27V9GF35N',
  );
}
